owner: jg-noncelogic
repo: rove-upptime

sites:
  - name: Rove Web
    url: https://roveapi.com
    expectedStatusCodes:
      - 200

  - name: Rove API
    url: https://rove-api.fly.dev/health
    expectedStatusCodes:
      - 200

  - name: Rove API (v1)
    url: https://rove-api.fly.dev/v1/account/usage
    expectedStatusCodes:
      - 401

status-website:
  cname: status.roveapi.com
  name: Rove Status
  theme: dark
  logoUrl: https://roveapi.com/icon
  favicon: https://roveapi.com/favicon.ico

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident Report
  liveStatus: Live Status
  overallUptime: Overall Uptime
  pastIncidents: Past Incidents
